### ISSUE TITLE
Initial suggestions for plugin release

### ISSUE THREAD

**Issue by madhushreeray30** [ip2location/steampipe-plugin-ip2locationio#1]
The basic structure looks good so far. While using the plugin, we did come up with a few suggestions based on our best practices:
- `ip2locationio.spc`
  - Could you please update the `ip2locationio.spc` file to follow the format of the [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/config/namecheap.spc
  - For instance:
  ```
   connection "ip2locationio" {
     plugin = "ip2location/ip2locationio"
     # API key for requests. Required.
     # Sign up for a free key at https://www.ip2location.io/pricing
     # api_key = "Q5Z8QS544RKC2VK4P3ZH7YW3C16MDCBW"
   }
  ```
- `docs/tables/*`
  - The example queries in the doc look a bit light. Could you please add 2-3 more example queries wherever possible?
 - `docs/index.md`
   - One example query is sufficient for `index.md` however we can go forward and add as many example queries as we want in the table docs
   - We have to keep a section `credentials` before the `configuration` section, we can take reference from the [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/docs/index.md)
   - Also please make sure that the [Configuration](https://github.com/ip2location/steampipe-plugin-ip2locationio/blob/main/docs/index.md#configuration) section is in sync with the changes suggested for the config/ip2locationio.spc file.
- `README`
   - One example query is sufficient for `README.md` however we can go forward and add as many example queries as we want in the table docs
   - The overall format looks good, a small suggestion would be to use `sh` instead of `shell` while putting down the CLI commands for instance
```sh
steampipe plugin install ip2location/ip2locationio
```
- `go.mod`
   - We should recompile the plugin with steampipe-plugin-sdk `v5.5.0`
- `ip2locationio/*`
   - The `connection_config.go`, `plugin.go` and `utils.go` seem to be quite well structured however why do we not use the environment variables for setting the api_key? Is there a way to authenticate with environment variables?
- `CHANGELOG.md`
   - Looks correct we can however keep the release date as `TBD`
- A couple of follow-up questions:
   - Is there a way to authenticate the api_key using environment variable? If yes, we need to mention explicitly in the `ip2locationio.spc`, `index.md` and `README.md` files
   - How are we handling the resource not found errors?
   - Do the APIs support pagination? I did not find any reference to it, but I want to make sure that we have checked that box before releasing it.
   - While working with the APIs did you encounter rate limit errors?
   - Please refer to https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion for more information
Please let us know if you have questions, happy to help :+1:

**Comment by ip2location-com** [comment]
@madhushreeray30 Thanks for your suggestions.

- Have added the environment variable
- We are returning the error as Error: Response
- The API does not support pagination
- There is no rate limit

**Comment by madhushreeray30** [comment]
@ip2location Thanks for the quick updates and fixes! 
Just a bit confused about the steampipe plugin install command you have used which is differently stated in the `index.md` and `README.md` files could you please look into this and get it updated? 
Ideally, I think it should be `steampipe plugin install ip2location/ip2locationio`.

**Comment by ip2location-com** [comment]
@madhushreeray30 Sorry, have updated the command.

**Comment by misraved** [comment]
Thanks @ip2location for this amazing plugin 👍. I was taking a final look at the plugin and had a few questions:
- Should the plugin be named `ip2location` instead of `ip2locationio`? We have similar plugin references like https://github.com/tomba-io/steampipe-plugin-tomba, https://github.com/turbot/steampipe-plugin-ipinfo etc. Please let us know what your thoughts are on this nomenclature.
- The formatting of the example queries should be updated using https://www.freeformatter.com/sql-formatter.html#before-output (2 spaces per indent level) to maintain consistency across all the plugins 👍. BTW the example queries look great!
- Could you please point me to the source of the environment variable? I tried searching for it in https://github.com/ip2location/ip2location-io-go but could not find any references to it.

**Comment by ip2location-com** [comment]
@misraved 
* We used ip2locationio because the API is from ip2location.io and not using the API from ip2location.com.
* Have reformatted the SQL using 2 spaces.
* The environment variable was introduced into the steampipe plugin as requested/suggested above. It does not exists in https://github.com/ip2location/ip2location-io-go.

**Comment by misraved** [comment]
Thanks @ip2location for this amazing new plugin 👍.

Please feel free to push a release tag (v0.0.1) and update the CHANGELOG file for the initial release 🎉 !!

**Comment by ip2location-com** [comment]
@misraved There appears to be an error in publishing.

![image](https://github.com/ip2location/steampipe-plugin-ip2locationio/assets/6367210/6d6424ba-71d4-4392-ba67-a5d24f960745)

**Comment by misraved** [comment]
@ip2location I don't think you need to add the `Build and Deploy OCI Image` workflow in the `.github` folder.

Once the release tag is pushed, we trigger a workflow to push the plugin to the hub 👍.

**Comment by ip2location-com** [comment]
@misraved Have deleted the `Build and Deploy OCI Image` workflow. Do I need to delete the tag and add it again?

**Comment by misraved** [comment]
No, you do not need to add a new tag 👍.

I have triggered the build process for this new plugin, it should be available on the hub in a while 👍.

**Comment by ip2location-com** [comment]
Just noticed that the icon and social graphic haven't been created.

**Comment by misraved** [comment]
Sorry for the delayed response @ip2location, I have fixed the issue of missing social graphics 👍.

The plugin is now available https://hub.steampipe.io/plugins/ip2location/ip2locationio.

Great work 🎉 !!

**Comment by ip2location-com** [comment]
@misraved Thanks for fixing the graphics!!

**Comment by misraved** [comment]
@ip2location thanks once again for creating the new plugin and for quickly addressing all the review comments. I believe this issue can now be closed 👍.

**Comment by ip2location-com** [comment]
@misraved Just saw this error. Is there anything that I need to do?

![image](https://github.com/ip2location/steampipe-plugin-ip2locationio/assets/6367210/3bfcba9e-1b90-4689-8bf4-f838a38f5e6b)

**Comment by misraved** [comment]
@ip2location you can remove the workflow from the `.github` folder since it relies on the workflows that point to a private repository 👍.
